apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: final-project
  labels:
    app: llm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-service
  template:
    metadata:
      labels:
        app: llm-service
    spec:
      volumes:
      - name: ollama-models
        hostPath:
          path: /usr/share/ollama/.ollama
          type: Directory
      containers:
      - name: llm-service
        image: prabal2011singh/interview-llm:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: ollama-models
          mountPath: /root/.ollama
        resources:
          requests:
            memory: "4Gi"
            cpu: "4"
          limits:
            memory: "6Gi"
            cpu: "6"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10